### ISSUE TITLE
Encoding for GPG

### ISSUE THREAD

**Issue by theithec** [stephenmcd/django-email-extras#20]
python-gnupg >= 0.3.6 uses "latin-1" as default encoding.
That makes `email_extras.utils.send_mail('Subject', '(U+015B): ś', ...` fail.

Possible fix: https://github.com/stephenmcd/django-email-extras/compare/master...theithec:master

**Comment by stephenmcd** [comment]
I merged your fix and pushed an new version to PyPI.

Thanks!
