### ISSUE TITLE
Add model relation and fingerprint

### ISSUE THREAD

**Issue by GeoTob** [stephenmcd/django-email-extras#26]
I think it would be handy to have a relation between `Key` and `Address`, so that if a `Key` is deleted, all corresponding instances of `Address` will be removed too.  

Also think it might be nice to store the Key fingerprint and display it in the admin panel's ListView, alongside the email addresses?

Can submit a PR for both , if you think those features are useful.

**Comment by stephenmcd** [comment]
Sounds good, thanks!
