### ISSUE TITLE
New PyPI Release?

### ISSUE THREAD

**Issue by ericamador** [stephenmcd/django-email-extras#44]
Hey Stephen,

Any chance we can get a new PyPI release soon? It appears that https://github.com/stephenmcd/django-email-extras/pull/42 is necessary for Django 1.11 support.

Thanks!

**Comment by RobinVanhove** [comment]
Also required for django2

**Comment by PhoenixAlx** [comment]
Please Stephen

new PyPI release

**Comment by bvermeule** [comment]
This is also needed for django-forms-builder email functionality. This is now broken on Django 1.10+

**Comment by ericamador** [comment]
@stephenmcd I haven't seen any activity here in a while. Should we consider this project dead?

**Comment by benzkji** [comment]
last commit is only a year ago...other priorities I guess. but a quick release would really not hurt that much ;-) please @stephenmcd

**Comment by benzkji** [comment]
installing with `-e git+https://github.com/etc...` - which is suboptimal, but works with django 1.11.

**Comment by bashu** [comment]
summoning @stephenmcd into thread

**Comment by stephenmcd** [comment]
Just pushed 0.3.4
